### ISSUE TITLE
Error message received: Request Timeout

### ISSUE THREAD

**Issue by TJJochen** [mrbungle64/ioBroker.ecovacs-deebot#120]
**Software version and sources:**

Adapter version: 1.0.10
Source/Repo: ioBroker Latest
Node.js version: v14.15.4
JS controller version: 3.2.7
Operating system: Debian 10
Hardware: Intel i5 NUC, Proxmox VM

**Model name:** Deebot Ozmo 900 series

**Please enter the following values:**

**"info.deviceClass":** y79a7u
"info.canvasModuleIsInstalled": true
"info.communicationProtocol": MQTT

**Describe the bug**

ecovacs-deebot.0 | 2021-01-23 09:55:59.701 | warn | (2675) Error message received: Request Timeout
ecovacs-deebot.0 | 2021-01-23 09:55:59.700 | warn | (2675) Error message received: Request Timeout
ecovacs-deebot.0 | 2021-01-23 09:55:59.700 | warn | (2675) Error message received: Request Timeout
ecovacs-deebot.0 | 2021-01-23 09:55:59.700 | warn | (2675) Error message received: Request Timeout
ecovacs-deebot.0 | 2021-01-23 09:55:59.700 | warn | (2675) Error message received: Request Timeout

This warning comes every hour

Edit: This is the VIS Logfile

**Heute** 10:20 | warn | ecovacs-deebot.0 | [1420 Einträge] Error message received: Request **Timeout**

**Comment by mrbungle64** [comment]
@TJJochen 

I also get these messages several times a day. I don't think that I can really do much about it, because it means that the Ecovacs server is not responding at that moment.
The adapter sends requests to the server at a certain interval, for which no response is received in this case.
You can adjust that interval in the adapter settings (possible values: 15, 30, 60 sec.)

Do you experience any problems in these cases or do you just want to report that warning messages?

**Comment by TJJochen** [comment]
**> Do you experience any problems in these cases or do you just want to report that warning messages?**

**@mrbungle64** 
I was already thinking that this is the connection to the Ecovacs server. It should only be a question, there are no problems with the adapter. Thanks and best regards Jochen
