### ISSUE TITLE
LastCleaningMapImageURL wird nicht gefüllt

### ISSUE THREAD

**Issue by uwe72** [mrbungle64/ioBroker.ecovacs-deebot#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues and no issue is describing my issue

### The problem

The state "LastCleaningMapImageURL" is empty.

Update: I read this is a known issue?

Are there chances that this will be fixed?

### With which model does the problem occur?

Deebot T9 series

### From which source you have installed the adapter?

Stable (default)

### Version of the ioBroker adapter ("info.version")

1.4.4

### Version of the ecovacs-deebot.js library ("info.library.version")

0.8.2

### Version of the JS controller

4.0.23

### Version of Node.js

14.18.3

### Operating system

Linux

### Anything in the logs that might be useful?

```txt
state "ecovacs-deebot.0.cleaninglog.lastCleaningMapImageURL" is always empty.

I would like to have a map like in the native app.

In the adapter settings i turned on all (in my opinion) related settings.

What can i do, can anybody help me?
```

**Comment by mrbungle64** [comment]
This issue is already listed in the ["Known issues" section](https://github.com/mrbungle64/ioBroker.ecovacs-deebot#known-issues) 
and there's also [another issue](https://github.com/mrbungle64/ioBroker.ecovacs-deebot/issues/270) related to this which is a "pinned" issue.

I don't own a T9 device but I'll still try to implement it also for the T9 series as well.

**Comment by uwe72** [comment]
sorry for the redundant ticket. Pls close if u want.
